exec-once = swww-daemon &
exec-once = waybar
exec-once = mako
exec-once = swaync
exec-once = hypridle
exec-once = gammastep -l 12.97:77.59 -t 6500:3000
exec-once = /usr/bin/kwalletd5
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = hyprpm reload

