# General
windowrule = float on, match:class ^(notification)$
windowrule = float on, match:class ^(confirm)$

# Kitty
windowrule = float on, center on, size 800 600, match:class ^(kitty)$

# Pavucontrol
windowrule = float on, size 600 400, center on, match:class ^(org.pulseaudio.pavucontrol)$

# Dolphin
# windowrule = float on, size 1600 900, match:class ^(org.kde.dolphin)$

# Blueman-Manager
windowrule = float on, size 600 400, center on, match:class ^(blueman-manager)$

# Wifi (iwgtk)
windowrule = float on, size 600 400, center on, match:class ^(org.twosheds.iwgtk)$

# File Picker
windowrule = float on, center on, size 600 400, match:class ^(xdg-desktop-portal-gtk)$

# Brave
# windowrule = float on, maximize on, match:class ^(brave-browser)$

# mpv (Video Player)
windowrule = float on, center on, size 1280 720, match:class ^(mpv)$

# TLauncher
windowrule = float on, match:class ^(org-tlauncher-tlauncher-rmo-TLauncher)$

# Swayimg
windowrule = float on, match:class ^(swayimg)$

